# Generated by Django 5.2 on 2025-05-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLATED', 'Completed'), ('FAILED', 'Failed'), ('COMPENSATED', 'Compansated')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
