# Generated by Django 5.2 on 2025-05-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('stock_id', models.PositiveBigIntegerField()),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
