# Generated by Django 5.2 on 2025-05-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
