# Generated by Django 5.2 on 2025-05-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='stock_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
