# Generated by Django 5.2 on 2025-05-02 03:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quanlity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField()),
                ('product_id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
