# Generated by Django 5.2 on 2025-05-02 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmodel',
            name='product_id',
        ),
    ]
